### ISSUE TITLE
Aggregate multiple ISSUE

### ISSUE THREAD

**Issue by iio1989** [iio1989/oshite#16]
## Template name
Aggregate multiple ISSUE

## About 
Here is a template for creating an issue

// Template content
// ## Overview
// Please provide an overview of the issue you are creating.
// ex) I want to adapt the style of the header.

## Purpose
Describe the purpose of this issue
ex) To style it.

## Task
Break down and manage your tasks.
- [x] [Delete Old Design #8](https://github.com/iio1989/oshite/issues/8)
- [x] [Runtime version up #11](https://github.com/iio1989/oshite/issues/11)
- [x] [header focus style #15](https://github.com/iio1989/oshite/issues/15)
- [x] [sns share](https://github.com/iio1989/oshite/issues/13)
- [x] [restructuring](https://github.com/iio1989/oshite/issues/17)

**Comment by iio1989** [comment]
done

https://github.com/iio1989/oshite/pull/18
