### ISSUE TITLE
Modification of conversion function

### ISSUE THREAD

**Issue by iio1989** [iio1989/oshite#26]
## Template name
Modification of conversion function

## About 
Add the following features

- Provide a choice of two types of image images.
- Allow users to select with or without ruby for each image.

// Template content
// ## Overview
// Please provide an overview of the issue you are creating.
// ex) I want to adapt the style of the header.

## Purpose
Describe the purpose of this issue
ex) To style it.

## Task
Break down and manage your tasks.
- [ ] Allow users to select with or without ruby for each image.
- [ ] Provide a choice of two types of image images.
- [ ] Make it possible to select with or without transparency.

**Comment by iio1989** [comment]
Just reconsidered,
I thought the only thing that should be done with this isssue is to allow the user to choose whether or not to have ruby.
- I thought that transparent images should only be downloaded in bulk.
- I thought that letters of different designs should only be distributed in batches.

**Comment by iio1989** [comment]
done
