### ISSUE TITLE
Implemented image list page

### ISSUE THREAD

**Issue by iio1989** [iio1989/oshite#28]
## Template name
Implemented image list page

## About 
Implement the following screen

- Add “がぞう” between “へんかん” and “せつめい”
- Display a list page of woshite characters (both with and without ruby).
- Added Google Drive links to publish images of entire letters and individual images

// Template content
// ## Overview
// Please provide an overview of the issue you are creating.
// ex) I want to adapt the style of the header.

## Purpose
Describe the purpose of this issue
ex) To style it.

## Task
Break down and manage your tasks.
- [ ] Add “がぞう” between “へんかん” and “せつめい”
- [ ] Display a list page of woshite characters (both with and without ruby).
- [ ] Added Google Drive links to publish images of entire letters and individual images
