### ISSUE TITLE
SEO support

### ISSUE THREAD

**Issue by iio1989** [iio1989/oshite#5]
## Template name
SEO support

## About 
SEO support

// Template content

## Purpose
Minimal search ranking improvement

## Task
Break down and manage your tasks.
- [ ] add meta description.
- [ ] add alt attribute for img.
- [ ] check h tag.
- [ ] check mobile friendly.
https://search.google.com/test/mobile-friendly
- [ ] check structured data.
https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data?hl=ja#structured-data-format
→pending
- [ ] 

## other
SEO check
https://ko-hyo-ka.com/

**Comment by iio1989** [comment]
done.
https://github.com/iio1989/oshite/pull/6
